

package org.jetbrains.exposed.compiler.plugin.runners;

import com.intellij.testFramework.TestDataPath;
import org.jetbrains.kotlin.test.util.KtTestUtil;
import org.jetbrains.kotlin.test.TargetBackend;
import org.jetbrains.kotlin.test.TestMetadata;
import org.junit.jupiter.api.Test;

import java.io.File;
import java.util.regex.Pattern;

/** This class is generated by {@link org.jetbrains.exposed.compiler.plugin.GenerateTestsKt}. DO NOT MODIFY MANUALLY */
@SuppressWarnings("all")
@TestMetadata("compiler-plugin/testData/box")
@TestDataPath("$PROJECT_ROOT")
public class JvmBoxTestGenerated extends AbstractJvmBoxTest {
  @Test
  public void testAllFilesPresentInBox() {
    KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("compiler-plugin/testData/box"), Pattern.compile("^(.+)\\.kt$"), null, TargetBackend.JVM_IR, true);
  }

  @Test
  @TestMetadata("exposed.kt")
  public void testExposed() {
    runTest("compiler-plugin/testData/box/exposed.kt");
  }

  @Test
  @TestMetadata("exposedIterable.kt")
  public void testExposedIterable() {
    runTest("compiler-plugin/testData/box/exposedIterable.kt");
  }

  @Test
  @TestMetadata("exposedLongIdTable.kt")
  public void testExposedLongIdTable() {
    runTest("compiler-plugin/testData/box/exposedLongIdTable.kt");
  }
}
